---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Run whoami without become.
      command: whoami
      changed_when: false
      become: false
      register: whoami
    - name: print whoami
      debug:
        var: whoami
        verbosity: 4
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
    - name: fix coreutils-single on containers
      command: dnf install -y --allowerasing coreutils
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version| int > 7
      changed_when: false
    - name: install iproute2
      package:
        name: iproute2
        state: present
      when:
        - ansible_os_family == 'Debian'
      changed_when: false
    - name: install iproute
      package:
        name: iproute
        state: present
      when:
        - ansible_os_family == 'RedHat'
      changed_when: false
    # debugging.
    - name: create cron.d
      file:
        path: /etc/cron.d
        state: directory
        mode: '0755'
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version| int > 7
    - name: re-run setup
      setup:
  roles:
    - {role: 'sdarwin.wordpress', run_update_packages: true}
    - {role: 'sdarwin.wordpress', run_deploy_users: true}
    - {role: 'sdarwin.wordpress', run_mysql: true}
    - {role: 'sdarwin.wordpress', run_email: true}
    - {role: 'sdarwin.wordpress', run_webserver: true}
    - {role: 'sdarwin.wordpress', run_wpapp: true}
  post_tasks:
    - name: Add www.example.com to hosts file
      shell: echo "127.0.1.1  www.example.com" >> /etc/hosts  # noqa 305
      changed_when: false

    - name: Check website
      uri:
        url: http://www.example.com/
        validate_certs: false
        return_content: true
      register: this
      failed_when: "'WordPress' not in this.content"
